channels:
  - conda-forge

dependencies:
  - python>=3.7,<3.10
  - c-compiler=1.0.4
  - cmake=3.14.0
  - qt=5.12.5
  - pip
  - pip:
    - numpy>=1.17.0,<2.0.0
    - gymnasium>=0.29.0
    - pybind11>=2.11.0
    - filelock>=3.0.0,<4.0.0
